#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the MicroAPRS2_user.mk file instead.
#

# Constants automatically defined by the selected modules
MicroAPRS2_DEBUG = 0

# Our target application
TRG += MicroAPRS2

MicroAPRS2_PREFIX = "/usr/bin/avr-"

MicroAPRS2_SUFFIX = ""

MicroAPRS2_SRC_PATH = MicroAPRS2

MicroAPRS2_HW_PATH = MicroAPRS2

# Files automatically generated by the wizard. DO NOT EDIT, USE MicroAPRS2_USER_CSRC INSTEAD!
MicroAPRS2_WIZARD_CSRC = \
	bertos/algo/crc_ccitt.c \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/cpu/avr/drv/ser_mega.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/cpu/avr/drv/timer_mega.c \
	bertos/drv/ser.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/net/afsk.c \
	bertos/net/ax25.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE MicroAPRS2_USER_PCSRC INSTEAD!
MicroAPRS2_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE MicroAPRS2_USER_CPPASRC INSTEAD!
MicroAPRS2_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE MicroAPRS2_USER_CXXSRC INSTEAD!
MicroAPRS2_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE MicroAPRS2_USER_ASRC INSTEAD!
MicroAPRS2_WIZARD_ASRC = \
	 \
	#

MicroAPRS2_CPPFLAGS = -D'CPU_FREQ=(16000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(MicroAPRS2_HW_PATH) -I$(MicroAPRS2_SRC_PATH) $(MicroAPRS2_CPU_CPPFLAGS) $(MicroAPRS2_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
MicroAPRS2_LDFLAGS = $(MicroAPRS2_CPU_LDFLAGS) $(MicroAPRS2_WIZARD_LDFLAGS) $(MicroAPRS2_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
MicroAPRS2_CPPAFLAGS = $(MicroAPRS2_CPU_CPPAFLAGS) $(MicroAPRS2_WIZARD_CPPAFLAGS) $(MicroAPRS2_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
MicroAPRS2_CSRC = $(MicroAPRS2_CPU_CSRC) $(MicroAPRS2_WIZARD_CSRC) $(MicroAPRS2_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
MicroAPRS2_PCSRC = $(MicroAPRS2_CPU_PCSRC) $(MicroAPRS2_WIZARD_PCSRC) $(MicroAPRS2_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
MicroAPRS2_CPPASRC = $(MicroAPRS2_CPU_CPPASRC) $(MicroAPRS2_WIZARD_CPPASRC) $(MicroAPRS2_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
MicroAPRS2_CXXSRC = $(MicroAPRS2_CPU_CXXSRC) $(MicroAPRS2_WIZARD_CXXSRC) $(MicroAPRS2_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
MicroAPRS2_ASRC = $(MicroAPRS2_CPU_ASRC) $(MicroAPRS2_WIZARD_ASRC) $(MicroAPRS2_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
MicroAPRS2_MCU = atmega328p
MicroAPRS2_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
MicroAPRS2_PROGRAMMER_CPU = atmega328p
MicroAPRS2_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
MicroAPRS2_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
MicroAPRS2_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
MicroAPRS2_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(MicroAPRS2_SRC_PATH)/MicroAPRS2_user.mk
